### ISSUE TITLE
HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND postgres

### ISSUE THREAD

**Issue by mika-data** [tryretool/retool-onpremise#153]
Tried to run retool-onpremise on SLES 15 SP3, via podman (not docker).

Version: 
```
REPOSITORY                                   TAG         IMAGE ID      CREATED        SIZE
localhost/retool-onpremise_db-ssh-connector  latest      64003f2c39a4  6 minutes ago  6.77 GB
localhost/retool-onpremise_db-connector      latest      64003f2c39a4  6 minutes ago  6.77 GB
localhost/retool-onpremise_api               latest      64003f2c39a4  6 minutes ago  6.77 GB
localhost/retool-onpremise_jobs-runner       latest      64003f2c39a4  6 minutes ago  6.77 GB
docker.io/tryretool/backend                  latest      05e223c92e0e  34 hours ago   6.77 GB
docker.io/tryretool/https-portal             latest      322af9d9c578  4 years ago    252 MB
docker.io/library/postgres                   9.6.5       bd287e105bc1  5 years ago    277 MB
```

LATEST = [2.107.4](https://hub.docker.com/layers/tryretool/backend/2.107.4/images/sha256-e717a8649dcff01ff6b5fc4bb001e66ffc08c19e3dc99a28daef5d9ab406334a?context=explore)

Log:

```
---------------------------
-     EXITING RETOOL      -
---------------------------

Error running database migrations: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND postgres
exit code: 1
{"message":"[process service types] MAIN_BACKEND","level":"info","timestamp":"2023-02-03T10:53:07.987Z"}
Failing checking database migrations
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND postgres
    at Client._connectionCallback (/snapshot/retool_development/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:173:24)
    at Client._handleErrorWhileConnecting (/snapshot/retool_development/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/snapshot/retool_development/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (node:events:526:28)
    at Socket.reportStreamError (/snapshot/retool_development/node_modules/pg/lib/connection.js:52:12)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  parent: Error: getaddrinfo ENOTFOUND postgres
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'postgres'
  },
  original: Error: getaddrinfo ENOTFOUND postgres
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'postgres'
  }
}



```

**Comment by haeusler** [comment]
I get exactly the same error when trying to run retool-onpremise on MacOS 12.6.5 via Rancher Desktop (1.8.1 with container enginer dockerd (moby))

**Comment by haeusler** [comment]
This happens when I follow the installation instructions documented on https://my.retool.com/:
![image](https://user-images.githubusercontent.com/575017/236300522-b03c27c5-808e-41e8-9994-11a95997c288.png)

As well as on https://retool.com/self-hosted/
![image](https://user-images.githubusercontent.com/575017/236300825-ee93ed07-79aa-4df0-881c-486607884ba6.png)

These docs point to an outdated version of the "easy install script":
https://raw.githubusercontent.com/tryretool/retool-onpremise/ssop/deploy-retool

This brings an outdated version of the docker-compose.yml, which tries to install an outdated version of postgres, which is not compatible with docker emulation on M1 macs.

**Comment by bdjohnson529** [comment]
Hi @mika-data, thanks for surfacing. We're tracking this issue internally - if you continue to run into roadblocks, please reach out to **support@retool.com**.
