### ISSUE TITLE
db-connector crashing

### ISSUE THREAD

**Issue by joshrendek** [tryretool/retool-onpremise#156]
After an initial install the db-connector docker container is looping with this error:

```
{"source":"master","pid":2523,"code":1,"signal":null,"heapStatistics":{"rss":367349760,"heapTotal":228044800,"heapUsed":217742696,"external":53797876,"arrayBuffers":35896084},"level":"info","message":"[Master] Worker died","timestamp":"2023-02-26T21:05:57.397Z"}
{"source":"master","pid":2529,"heapStatistics":{"rss":367374336,"heapTotal":228044800,"heapUsed":217770416,"external":53797876,"arrayBuffers":35896084},"level":"info","message":"[Master] Started worker","timestamp":"2023-02-26T21:05:57.429Z"}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/retool_backend/--max-http-header-size=80000'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1912:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

This presents itself in the UI when trying to test a connection:

![image](https://user-images.githubusercontent.com/36339/221437386-26b59120-784d-45d6-b474-b0870f7d0789.png)

**Comment by theMiddleBlue** [comment]
same issue here

**Comment by kamorozov** [comment]
Same for me. Did someone test previous versions?

**Comment by octobocto** [comment]
Same issue here
