### ISSUE TITLE
Heroku Push Button - License Key Error

### ISSUE THREAD

**Issue by davertron** [tryretool/retool-onpremise#26]
I did the Heroku deploy via the push button from the README and the app wouldn't start up. The logs showed the following error:

```
2020-08-05T16:10:21.904423+00:00 app[web.1]: Encountered error
2020-08-05T16:10:21.904924+00:00 app[web.1]: Error: No license key was provided.
2020-08-05T16:10:21.904925+00:00 app[web.1]:     at checkLicenseStatus (/snapshot/retool/server/modules/licensing.js:0:0)
2020-08-05T16:10:21.904926+00:00 app[web.1]:     at startOnPremServer (/snapshot/retool/server/main.js:0:0)
2020-08-05T16:10:21.904927+00:00 app[web.1]:     at main (/snapshot/retool/server/main.js:0:0)
2020-08-05T16:10:21.904927+00:00 app[web.1]:     at Object.<anonymous> (/snapshot/retool/server/main.js:0:0)
2020-08-05T16:10:21.904927+00:00 app[web.1]:     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
2020-08-05T16:10:21.904928+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2020-08-05T16:10:21.904928+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:651:32)
2020-08-05T16:10:21.904928+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
2020-08-05T16:10:21.904929+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:583:3)
2020-08-05T16:10:21.904929+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:690:17)
2020-08-05T16:10:21.904930+00:00 app[web.1]:     at Module.require (pkg/prelude/bootstrap.js:1166:31)
2020-08-05T16:10:21.904930+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:25:18)
2020-08-05T16:10:21.904930+00:00 app[web.1]:     at Object.<anonymous> (/snapshot/retool/main.js:0:0)
2020-08-05T16:10:21.904931+00:00 app[web.1]:     at Module._compile (pkg/prelude/bootstrap.js:1261:22)
2020-08-05T16:10:21.904931+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
2020-08-05T16:10:21.904931+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:651:32)
2020-08-05T16:10:21.904932+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
2020-08-05T16:10:21.904932+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:583:3)
2020-08-05T16:10:21.904933+00:00 app[web.1]:     at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
2020-08-05T16:10:21.904933+00:00 app[web.1]:     at startup (internal/bootstrap/node.js:320:19)
2020-08-05T16:10:21.904933+00:00 app[web.1]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)
2020-08-05T16:10:21.904990+00:00 app[web.1]: Exiting...
2020-08-05T16:10:22.027840+00:00 heroku[web.1]: Process exited with status 0
2020-08-05T16:10:22.070759+00:00 heroku[web.1]: State changed from starting to crashed
```

I was able to fix this by adding a `LICENSE_KEY` env variable manually in my Heroku config, but that was just a lucky guess, even the manual Heroku setup in the README doesn't mention adding that env variable.

**Comment by AustinMoninger** [comment]
Added LICENSE_KEY to the Heroku docs — thanks for the suggestion
