### ISSUE TITLE
First Launch Race Condition?

### ISSUE THREAD

**Issue by davertron** [tryretool/retool-onpremise#29]
I've noticed that sometimes Retool doesn't start up properly on first launch. It looks like a race condition between the `api` container and the `jobs-runner` container, where the `api` container is trying to query a table that doesn't exist yet. In the logs below you can see the `api` container throwing SQL errors, and then if you keep going down you'll eventually see the `jobs-runner` finish the migration of the audit trail tables. The `api` container will try a few times and then will quit. If I wait for the `jobs-runner` to run the migrations, then restart the `api` container manually, everything works fine.

```
api_1               | wait-for-it.sh: waiting 15 seconds for postgres:5432
api_1               | wait-for-it.sh: postgres:5432 is available after 6 seconds
api_1               | not untarring the bundle
api_1               | NODE_ENV: 'production'
api_1               | COOKIE_INSECURE: true
api_1               | Setting http and https agent maxSockets to 25
api_1               | Running node v10.21.0
api_1               | ARGV: []
api_1               | Tue, 01 Sep 2020 19:51:26 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at ../snapshot/retool/node_modules/sequelize/lib/sequelize.js:242:13
api_1               | Tue, 01 Sep 2020 19:51:30 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at ../snapshot/retool/server/app.js:0:0
api_1               | Tue, 01 Sep 2020 19:51:30 GMT body-parser deprecated undefined extended: provide extended option at ../snapshot/retool/node_modules/body-parser/index.js:105:29
api_1               | main web boot-up: 10068.976ms
api_1               | [pid: 33] Memory Stats for process:  { rss: '187.723776 MB',
api_1               |   heapTotal: '159.031296 MB',
api_1               |   heapUsed: '128.337856 MB',
api_1               |   percentageHeapUsed: '80.7%' }
api_1               | [pid: 33] CPU Usage % for process:  12.34%
api_1               | [pid: 33] Memory Stats for container:  { freeSystemMemory: '66.572288 MB',
api_1               |   totalSystemMemory: '1031.131136 MB',
api_1               |   percentageFreeMemory: '6.43%' }
api_1               | Rechecking license status...
api_1               | Encountered error
api_1               | { SequelizeDatabaseError: relation "audit_trail_events" does not exist
api_1               |     at Query.formatError (/snapshot/retool/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
api_1               |     at run.query.catch.err (/snapshot/retool/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
api_1               |     at tryCatcher (/snapshot/retool/node_modules/bluebird/js/release/util.js:16:23)
api_1               |     at Promise.module.exports.Promise._settlePromiseFromHandler (/snapshot/retool/node_modules/bluebird/js/release/promise.js:547:31)
api_1               |     at Promise.module.exports.Promise._settlePromise (/snapshot/retool/node_modules/bluebird/js/release/promise.js:604:18)
api_1               |     at Promise.module.exports.Promise._settlePromise0 (/snapshot/retool/node_modules/bluebird/js/release/promise.js:649:10)
api_1               |     at Promise.module.exports.Promise._settlePromises (/snapshot/retool/node_modules/bluebird/js/release/promise.js:725:18)
api_1               |     at _drainQueueStep (/snapshot/retool/node_modules/bluebird/js/release/async.js:93:12)
api_1               |     at _drainQueue (/snapshot/retool/node_modules/bluebird/js/release/async.js:86:9)
api_1               |     at Async._drainQueues (/snapshot/retool/node_modules/bluebird/js/release/async.js:102:5)
api_1               |     at Immediate.Async.drainQueues [as _onImmediate] (/snapshot/retool/node_modules/bluebird/js/release/async.js:15:14)
api_1               |     at runCallback (timers.js:705:18)
api_1               |     at tryOnImmediate (timers.js:676:5)
api_1               |     at processImmediate (timers.js:658:5)
api_1               |     at process.topLevelDomainCallback (domain.js:126:23)
api_1               |   name: 'SequelizeDatabaseError',
api_1               |   parent:
api_1               |    { error: relation "audit_trail_events" does not exist
api_1               |        at Connection.parseE (/snapshot/retool/node_modules/pg/lib/connection.js:614:13)
api_1               |        at Connection.parseMessage (/snapshot/retool/node_modules/pg/lib/connection.js:413:19)
api_1               |        at Socket.<anonymous> (/snapshot/retool/node_modules/pg/lib/connection.js:129:22)
api_1               |        at Socket.emit (events.js:198:13)
api_1               |        at Socket.EventEmitter.emit (domain.js:448:20)
api_1               |        at addChunk (_stream_readable.js:288:12)
api_1               |        at readableAddChunk (_stream_readable.js:269:11)
api_1               |        at Socket.Readable.push (_stream_readable.js:224:10)
api_1               |        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
api_1               |      name: 'error',
api_1               |      length: 117,
api_1               |      severity: 'ERROR',
api_1               |      code: '42P01',
api_1               |      detail: undefined,
api_1               |      hint: undefined,
api_1               |      position: '40',
api_1               |      internalPosition: undefined,
api_1               |      internalQuery: undefined,
api_1               |      where: undefined,
api_1               |      schema: undefined,
api_1               |      table: undefined,
api_1               |      column: undefined,
api_1               |      dataType: undefined,
api_1               |      constraint: undefined,
api_1               |      file: 'parse_relation.c',
api_1               |      line: '1160',
api_1               |      routine: 'parserOpenTable',
api_1               |      sql:
api_1               |       'SELECT distinct(email)\n    FROM users, audit_trail_events\n    WHERE users.id = audit_trail_events."userId"\n    AND audit_trail_events."createdAt" > (now() - interval \'1 day\')' },
api_1               |   original:
api_1               |    { error: relation "audit_trail_events" does not exist
api_1               |        at Connection.parseE (/snapshot/retool/node_modules/pg/lib/connection.js:614:13)
api_1               |        at Connection.parseMessage (/snapshot/retool/node_modules/pg/lib/connection.js:413:19)
api_1               |        at Socket.<anonymous> (/snapshot/retool/node_modules/pg/lib/connection.js:129:22)
api_1               |        at Socket.emit (events.js:198:13)
api_1               |        at Socket.EventEmitter.emit (domain.js:448:20)
api_1               |        at addChunk (_stream_readable.js:288:12)
api_1               |        at readableAddChunk (_stream_readable.js:269:11)
api_1               |        at Socket.Readable.push (_stream_readable.js:224:10)
api_1               |        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
api_1               |      name: 'error',
api_1               |      length: 117,
api_1               |      severity: 'ERROR',
api_1               |      code: '42P01',
api_1               |      detail: undefined,
api_1               |      hint: undefined,
api_1               |      position: '40',
api_1               |      internalPosition: undefined,
api_1               |      internalQuery: undefined,
api_1               |      where: undefined,
api_1               |      schema: undefined,
api_1               |      table: undefined,
api_1               |      column: undefined,
api_1               |      dataType: undefined,
api_1               |      constraint: undefined,
api_1               |      file: 'parse_relation.c',
api_1               |      line: '1160',
api_1               |      routine: 'parserOpenTable',
[root@ip-172-31-4-13 retool-onpremise]# docker-compose logs | grep -E "(api_1|jobs-runner_1)" | head -n 200
Attaching to retool-onpremise_https-portal_1, retool-onpremise_api_1, retool-onpremise_jobs-runner_1, retool-onpremise_db-ssh-connector_1, retool-onpremise_db-connector_1, retool-onpremise_postgres_1, retool-onpremise_user-postgres_1
api_1               | wait-for-it.sh: waiting 15 seconds for postgres:5432
api_1               | wait-for-it.sh: postgres:5432 is available after 6 seconds
api_1               | not untarring the bundle
api_1               | NODE_ENV: 'production'
api_1               | COOKIE_INSECURE: true
api_1               | Setting http and https agent maxSockets to 25
api_1               | Running node v10.21.0
api_1               | ARGV: []
api_1               | Tue, 01 Sep 2020 19:51:26 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at ../snapshot/retool/node_modules/sequelize/lib/sequelize.js:242:13
api_1               | Tue, 01 Sep 2020 19:51:30 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at ../snapshot/retool/server/app.js:0:0
api_1               | Tue, 01 Sep 2020 19:51:30 GMT body-parser deprecated undefined extended: provide extended option at ../snapshot/retool/node_modules/body-parser/index.js:105:29
api_1               | main web boot-up: 10068.976ms
api_1               | [pid: 33] Memory Stats for process:  { rss: '187.723776 MB',
api_1               |   heapTotal: '159.031296 MB',
api_1               |   heapUsed: '128.337856 MB',
api_1               |   percentageHeapUsed: '80.7%' }
api_1               | [pid: 33] CPU Usage % for process:  12.34%
api_1               | [pid: 33] Memory Stats for container:  { freeSystemMemory: '66.572288 MB',
api_1               |   totalSystemMemory: '1031.131136 MB',
api_1               |   percentageFreeMemory: '6.43%' }
api_1               | Rechecking license status...
api_1               | Encountered error
api_1               | { SequelizeDatabaseError: relation "audit_trail_events" does not exist
api_1               |     at Query.formatError (/snapshot/retool/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
api_1               |     at run.query.catch.err (/snapshot/retool/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
api_1               |     at tryCatcher (/snapshot/retool/node_modules/bluebird/js/release/util.js:16:23)
api_1               |     at Promise.module.exports.Promise._settlePromiseFromHandler (/snapshot/retool/node_modules/bluebird/js/release/promise.js:547:31)
api_1               |     at Promise.module.exports.Promise._settlePromise (/snapshot/retool/node_modules/bluebird/js/release/promise.js:604:18)
api_1               |     at Promise.module.exports.Promise._settlePromise0 (/snapshot/retool/node_modules/bluebird/js/release/promise.js:649:10)
api_1               |     at Promise.module.exports.Promise._settlePromises (/snapshot/retool/node_modules/bluebird/js/release/promise.js:725:18)
api_1               |     at _drainQueueStep (/snapshot/retool/node_modules/bluebird/js/release/async.js:93:12)
api_1               |     at _drainQueue (/snapshot/retool/node_modules/bluebird/js/release/async.js:86:9)
api_1               |     at Async._drainQueues (/snapshot/retool/node_modules/bluebird/js/release/async.js:102:5)
api_1               |     at Immediate.Async.drainQueues [as _onImmediate] (/snapshot/retool/node_modules/bluebird/js/release/async.js:15:14)
api_1               |     at runCallback (timers.js:705:18)
api_1               |     at tryOnImmediate (timers.js:676:5)
api_1               |     at processImmediate (timers.js:658:5)
api_1               |     at process.topLevelDomainCallback (domain.js:126:23)
api_1               |   name: 'SequelizeDatabaseError',
api_1               |   parent:
api_1               |    { error: relation "audit_trail_events" does not exist
api_1               |        at Connection.parseE (/snapshot/retool/node_modules/pg/lib/connection.js:614:13)
api_1               |        at Connection.parseMessage (/snapshot/retool/node_modules/pg/lib/connection.js:413:19)
api_1               |        at Socket.<anonymous> (/snapshot/retool/node_modules/pg/lib/connection.js:129:22)
api_1               |        at Socket.emit (events.js:198:13)
api_1               |        at Socket.EventEmitter.emit (domain.js:448:20)
api_1               |        at addChunk (_stream_readable.js:288:12)
api_1               |        at readableAddChunk (_stream_readable.js:269:11)
api_1               |        at Socket.Readable.push (_stream_readable.js:224:10)
api_1               |        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
api_1               |      name: 'error',
api_1               |      length: 117,
api_1               |      severity: 'ERROR',
api_1               |      code: '42P01',
api_1               |      detail: undefined,
api_1               |      hint: undefined,
api_1               |      position: '40',
api_1               |      internalPosition: undefined,
api_1               |      internalQuery: undefined,
api_1               |      where: undefined,
api_1               |      schema: undefined,
api_1               |      table: undefined,
api_1               |      column: undefined,
api_1               |      dataType: undefined,
api_1               |      constraint: undefined,
api_1               |      file: 'parse_relation.c',
api_1               |      line: '1160',
api_1               |      routine: 'parserOpenTable',
api_1               |      sql:
api_1               |       'SELECT distinct(email)\n    FROM users, audit_trail_events\n    WHERE users.id = audit_trail_events."userId"\n    AND audit_trail_events."createdAt" > (now() - interval \'1 day\')' },
api_1               |   original:
api_1               |    { error: relation "audit_trail_events" does not exist
api_1               |        at Connection.parseE (/snapshot/retool/node_modules/pg/lib/connection.js:614:13)
api_1               |        at Connection.parseMessage (/snapshot/retool/node_modules/pg/lib/connection.js:413:19)
api_1               |        at Socket.<anonymous> (/snapshot/retool/node_modules/pg/lib/connection.js:129:22)
api_1               |        at Socket.emit (events.js:198:13)
api_1               |        at Socket.EventEmitter.emit (domain.js:448:20)
api_1               |        at addChunk (_stream_readable.js:288:12)
api_1               |        at readableAddChunk (_stream_readable.js:269:11)
api_1               |        at Socket.Readable.push (_stream_readable.js:224:10)
api_1               |        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
api_1               |      name: 'error',
api_1               |      length: 117,
api_1               |      severity: 'ERROR',
api_1               |      code: '42P01',
api_1               |      detail: undefined,
api_1               |      hint: undefined,
api_1               |      position: '40',
jobs-runner_1       | wait-for-it.sh: waiting 15 seconds for postgres:5432
jobs-runner_1       | wait-for-it.sh: postgres:5432 is available after 8 seconds
jobs-runner_1       | not untarring the bundle
jobs-runner_1       | yarn run v1.22.4
jobs-runner_1       | warning package.json: Potential typo "script", did you mean "scripts"?
jobs-runner_1       | warning package.json: License should be a valid SPDX license expression
jobs-runner_1       | $ ./node_modules/.bin/sequelize --config ./server/config/config.js db:migrate
jobs-runner_1       |
jobs-runner_1       | Sequelize CLI [Node: 10.22.0, CLI: 4.0.0, ORM: 4.43.0]
jobs-runner_1       |
jobs-runner_1       | NODE_ENV: 'production'
jobs-runner_1       | COOKIE_INSECURE: true
jobs-runner_1       | Loaded configuration file "server/config/config.js".
jobs-runner_1       | Using environment "production".
jobs-runner_1       | Tue, 01 Sep 2020 19:51:29 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
jobs-runner_1       | == 20170517054913-create-organization-and-user: migrating =======
jobs-runner_1       | == 20170517054913-create-organization-and-user: migrated (0.188s)
jobs-runner_1       |
jobs-runner_1       | == 20170519200903-create-page: migrating =======
jobs-runner_1       | == 20170519200903-create-page: migrated (0.089s)
jobs-runner_1       |
jobs-runner_1       | == 20170519213338-create-page-save: migrating =======
jobs-runner_1       | == 20170519213338-create-page-save: migrated (0.035s)
jobs-runner_1       |
jobs-runner_1       | == 20170521042445-create-resource: migrating =======
jobs-runner_1       | == 20170521042445-create-resource: migrated (0.217s)
jobs-runner_1       |
jobs-runner_1       | == 20170605055605-remove-non-null-constraint-on-organizations-domain: migrating =======
jobs-runner_1       | == 20170605055605-remove-non-null-constraint-on-organizations-domain: migrated (0.071s)
jobs-runner_1       |
jobs-runner_1       | == 20170626044218-relax-constraints-for-non-db-resources: migrating =======
jobs-runner_1       | == 20170626044218-relax-constraints-for-non-db-resources: migrated (0.138s)
jobs-runner_1       |
jobs-runner_1       | == 20170627021252-change-user-google-token-to-text-type: migrating =======
jobs-runner_1       | == 20170627021252-change-user-google-token-to-text-type: migrated (0.306s)
jobs-runner_1       |
jobs-runner_1       | == 20170718030743-create-embed: migrating =======
jobs-runner_1       | == 20170718030743-create-embed: migrated (0.025s)
jobs-runner_1       |
jobs-runner_1       | == 20170725114241-create-retool-tables: migrating =======
jobs-runner_1       | == 20170725114241-create-retool-tables: migrated (0.049s)
jobs-runner_1       |
jobs-runner_1       | == 20170801045015-add-database-id-table-name-uniq-constraint: migrating =======
jobs-runner_1       | == 20170801045015-add-database-id-table-name-uniq-constraint: migrated (0.028s)
jobs-runner_1       |
jobs-runner_1       | == 20170801051119-add-ssl-column-to-resources: migrating =======
jobs-runner_1       | == 20170801051119-add-ssl-column-to-resources: migrated (0.062s)
jobs-runner_1       |
jobs-runner_1       | == 20170827134431-add-edit-privilege-to-resources: migrating =======
jobs-runner_1       | == 20170827134431-add-edit-privilege-to-resources: migrated (0.054s)
jobs-runner_1       |
jobs-runner_1       | == 20170901033536-create-user-invites: migrating =======
jobs-runner_1       | == 20170901033536-create-user-invites: migrated (0.100s)
jobs-runner_1       |
jobs-runner_1       | == 20170904120915-add-option-column-to-resource: migrating =======
jobs-runner_1       | == 20170904120915-add-option-column-to-resource: migrated (0.027s)
jobs-runner_1       |
jobs-runner_1       | == 20170905163559-add-claimed-data-to-user-invites: migrating =======
jobs-runner_1       | == 20170905163559-add-claimed-data-to-user-invites: migrated (0.031s)
jobs-runner_1       |
jobs-runner_1       | == 20170908044721-camel-case-organization-id: migrating =======
jobs-runner_1       | == 20170908044721-camel-case-organization-id: migrated (0.620s)
jobs-runner_1       |
jobs-runner_1       | == 20170908045940-camel-case-foreign-keys: migrating =======
jobs-runner_1       | == 20170908045940-camel-case-foreign-keys: migrated (1.859s)
jobs-runner_1       |
jobs-runner_1       | == 20170908072236-create-groups: migrating =======
jobs-runner_1       | == 20170908072236-create-groups: migrated (0.057s)
jobs-runner_1       |
jobs-runner_1       | == 20170910220055-create-group-pages: migrating =======
jobs-runner_1       | == 20170910220055-create-group-pages: migrated (0.058s)
jobs-runner_1       |
jobs-runner_1       | == 20170911174211-add-unique-constraints-to-group-relations: migrating =======
jobs-runner_1       | == 20170911174211-add-unique-constraints-to-group-relations: migrated (0.075s)
jobs-runner_1       |
jobs-runner_1       | == 20170913082842-change-json-columns-to-jsonb: migrating =======
jobs-runner_1       | == 20170913082842-change-json-columns-to-jsonb: migrated (0.190s)
jobs-runner_1       |
jobs-runner_1       | == 20171007195513-create-user-invite-groups: migrating =======
jobs-runner_1       | == 20171007195513-create-user-invite-groups: migrated (0.065s)
jobs-runner_1       |
jobs-runner_1       | == 20171128020917-add-password-to-embeds: migrating =======
jobs-runner_1       | == 20171128020917-add-password-to-embeds: migrated (0.048s)
jobs-runner_1       |
jobs-runner_1       | == 20171211042535-add-verified-to-organizations: migrating =======
jobs-runner_1       | == 20171211042535-add-verified-to-organizations: migrated (0.049s)
jobs-runner_1       |
jobs-runner_1       | == 20171211043343-add-unique-constraint-to-organizations-name: migrating =======
jobs-runner_1       | == 20171211043343-add-unique-constraint-to-organizations-name: migrated (0.127s)
jobs-runner_1       |
jobs-runner_1       | == 20180105093546-create-audit-trail: migrating =======
jobs-runner_1       | == 20180105093546-create-audit-trail: migrated (0.158s)
```

**Comment by AustinMoninger** [comment]
I haven't encountered this with any customers recently so I'm going to go ahead and close this one out, but let us know if this continues to persist!

**Comment by olivierlefloch** [comment]
I just encountered this issue with the self hosted k8s deployment – in fact, since I created the job runner pod so soon after the Postgres pod, the job runner was unable to find Postgres. It does sound like handling these race conditions with automatic retries may make deployment easier.
